name: Enhanced Vulnerability Scan

on:
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild even if vulnerabilities were recently scanned'
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test vulnerability workflow
        run: echo "Enhanced vulnerability scan workflow is working!"