name: Docker Scout Vulnerability Scan 2

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  scan:
    runs-on: ubuntu-latest
    environment: DEFAULT  # Use the DEFAULT environment where IMAGE_NAME is stored

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull ${{ vars.IMAGE_NAME }}:latest

      - name: Analyze for critical and high CVEs with Docker Scout
        id: docker-scout-cves
        uses: docker/scout-action@v1
        with:
          image: ${{ vars.IMAGE_NAME }}:latest
          command: cves
          sarif-file: sarif.output.json  # Generate SARIF file for the scan result
          summary: true

      - name: Upload SARIF result to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json
