name: Update Docker Hub Description
on:
  workflow_dispatch:

jobs:
  update-dockerhub-description:
    runs-on: ubuntu-latest
    environment: DEFAULT
    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}  # Set the IMAGE_NAME environment variable using your GitHub variable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace Version Placeholders
        run: |
          # Ensure the file docker-hub-description.md exists
          if [[ ! -f docker-hub-description.md ]]; then
            echo "Error: docker-hub-description.md not found!"
            exit 1
          fi
          
          # Replace placeholders with actual version values
          sed -i "s/<!--BUILD_DATE-->.*<!--BUILD_DATE-->/<!--BUILD_DATE-->$(date +'%Y-%m-%d')<!--BUILD_DATE-->/g" docker-hub-description.md
          sed -i "s/<!--ALPINE_VERSION-->.*<!--ALPINE_VERSION-->/<!--ALPINE_VERSION-->3.15.0<!--ALPINE_VERSION-->/g" docker-hub-description.md
          sed -i "s/<!--NGINX_VERSION-->.*<!--NGINX_VERSION-->/<!--NGINX_VERSION-->1.21.6<!--NGINX_VERSION-->/g" docker-hub-description.md
          sed -i "s/<!--MODSECURITY_VERSION-->.*<!--MODSECURITY_VERSION-->/<!--MODSECURITY_VERSION-->v3.0.5<!--MODSECURITY_VERSION-->/g" docker-hub-description.md
          sed -i "s/<!--OWASP_RULESET_VERSION-->.*<!--OWASP_RULESET_VERSION-->/<!--OWASP_RULESET_VERSION-->v3.3.2<!--OWASP_RULESET_VERSION-->/g" docker-hub-description.md

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_RWD_PAT }}
          repository: ${{ env.IMAGE_NAME }}  # Use the environment variable for the image name
          readme-filepath: docker-hub-description.md  # Path to your description file
