name: Update Docker Hub Description
on:
  workflow_dispatch:

jobs:
  update-dockerhub-description:
    runs-on: ubuntu-latest
    environment: DEFAULT
    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}  # Set the IMAGE_NAME environment variable using your GitHub variable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Replace Version Placeholders
        run: |
          # Ensure the file docker-hub-description.md exists
          if [[ ! -f docker-hub-description.md ]]; then
            echo "Error: docker-hub-description.md not found!"
            exit 1
          fi
          
          # Replace placeholders with actual version values
          sed -i "s/<!--BUILD_DATE-->.*<!--BUILD_DATE-->/<!--BUILD_DATE-->$(date +'%Y-%m-%d')<!--BUILD_DATE-->/g" docker-hub-description.md
          sed -i "s/<!--ALPINE_VERSION-->.*<!--ALPINE_VERSION-->/<!--ALPINE_VERSION-->3.15.0<!--ALPINE_VERSION-->/g" docker-hub-description.md
          sed -i "s/<!--NGINX_VERSION-->.*<!--NGINX_VERSION-->/<!--NGINX_VERSION-->1.21.6<!--NGINX_VERSION-->/g" docker-hub-description.md
          sed -i "s/<!--MODSECURITY_VERSION-->.*<!--MODSECURITY_VERSION-->/<!--MODSECURITY_VERSION-->v3.0.5<!--MODSECURITY_VERSION-->/g" docker-hub-description.md
          sed -i "s/<!--OWASP_RULESET_VERSION-->.*<!--OWASP_RULESET_VERSION-->/<!--OWASP_RULESET_VERSION-->v3.3.2<!--OWASP_RULESET_VERSION-->/g" docker-hub-description.md

          echo "Updated content with version information:"
          cat docker-hub-description.md

      - name: Update Docker Hub README
        run: |
          # Update Docker Hub description using the content of docker-hub-description.md
          curl -s -X PATCH -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
            -H "Content-Type: application/json" \
            -d "{\"full_description\": \"$(jq -Rs . < docker-hub-description.md)\"}" \
            "https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/"
          
          echo "Docker Hub README updated successfully with content from docker-hub-description.md."
